### PR TITLE
Submit paper:  Using GitLab Issues for Iterative, Asynchronous Software Design

### PR DESCRIPTION
**Pull request by jmgate**
Add my paper to the list of whitepapers, and correct the heading to have the correct year.

### CODE REVIEW

**Comment by maherou** [comment]
Thank you, @jmgate

**Comment by jmgate** [comment]
Thanks for the merge, @maherou.  Quick question for you:  When I finally got this through R&A, I mentioned it to some contacts at GitLab, and they're eager to promote the piece in some way.  Is that something they can do now, or should we hold off on that till after CW23 next July?

**Comment by jmgate** [comment]
@jwillenbring, do you have any thoughts on the question above?

**Comment by maherou** [comment]
Hi @jmgate, I wonder if something like the US RSE Slack workspace would be a good forum: https://us-rse.org/resources/rses/

**Pull request merged**
